### ISSUE TITLE
request: ap image for dogstatsd

### ISSUE THREAD

**Issue by howardyoo** [astronomer/ap-vendor#391]
# What is dogstatsd
Dogstatsd (https://hub.docker.com/r/datadog/dogstatsd) is a varient of datadog agent (https://www.datadoghq.com/) which listens for statsd/dogstatsd metrics and forwards it to datadog service.

# Why is this image needed?
observability team is currently working in creating feature called 'airflow metrics export to 3rd party vendor) that can forward the statsd metrics coming from airflow (in Astro deployment) to DataDog. team is currently working with harmony and airflow operator team to create the necessary config and deployment for this feature, in order to install and run dogstatsd as a sidecar container inside the statsd pod, we need to have this vendor imaged and pushed into quay.io.

# What are the configuration?
here's the `Dockerfile` definition for this particular image:
```
# dockerfile to generate ap datadog agent suitable for airflow
FROM datadog/dogstatsd:7
COPY --chown=root:root dogstatsd.yaml /etc/datadog-agent/dogstatsd.yaml
```

and here's the `dogstatsd.yaml` file required to build Dockerfile
```
## Provides sane defaults, to be overridden by environment variables

# Required for probe.sh
health_port: 5555

# Gohai does not support alpine
enable_gohai: false

# dogstatsd_mapper_cache_size: 1000  # default to 1000
dogstatsd_mapper_profiles:
  - name: airflow
    prefix: "airflow."
    mappings:
      - match: "airflow.*_start"
        name: "airflow.job.start"
        tags:
          job_name: "$1"
      - match: "airflow.*_end"
        name: "airflow.job.end"
        tags:
          job_name: "$1"
      - match: "airflow.*_heartbeat_failure"
        name: airflow.job.heartbeat.failure
        tags:
          job_name: "$1"
      - match: "airflow.operator_failures_*"
        name: "airflow.operator_failures"
        tags:
          operator_name: "$1"
      - match: "airflow.operator_successes_*"
        name: "airflow.operator_successes"
        tags:
          operator_name: "$1"
      - match: 'airflow\.dag_processing\.last_runtime\.(.*)'
        match_type: "regex"
        name: "airflow.dag_processing.last_runtime"
        tags:
          dag_file: "$1"
      - match: 'airflow\.dag_processing\.last_run\.seconds_ago\.(.*)'
        match_type: "regex"
        name: "airflow.dag_processing.last_run.seconds_ago"
        tags:
          dag_file: "$1"
      - match: 'airflow\.dag\.loading-duration\.(.*)'
        match_type: "regex"
        name: "airflow.dag.loading_duration"
        tags:
          dag_file: "$1"
      - match: "airflow.dagrun.*.first_task_scheduling_delay"
        name: "airflow.dagrun.first_task_scheduling_delay"
        tags:
          dag_id: "$1"
      - match: "airflow.pool.open_slots.*"
        name: "airflow.pool.open_slots"
        tags:
          pool_name: "$1"
      - match: "airflow.pool.queued_slots.*"
        name: "airflow.pool.queued_slots"
        tags:
          pool_name: "$1"
      - match: "airflow.pool.running_slots.*"
        name: "airflow.pool.running_slots"
        tags:
          pool_name: "$1"
      - match: "airflow.pool.used_slots.*"
        name: "airflow.pool.used_slots"
        tags:
          pool_name: "$1"
      - match: "airflow.pool.starving_tasks.*"
        name: "airflow.pool.starving_tasks"
        tags:
          pool_name: "$1"
      - match: 'airflow\.dagrun\.dependency-check\.(.*)'
        match_type: "regex"
        name: "airflow.dagrun.dependency_check"
        tags:
          dag_id: "$1"
      - match: 'airflow\.dag\.(.*)\.([^.]*)\.duration'
        match_type: "regex"
        name: "airflow.dag.task.duration"
        tags:
          dag_id: "$1"
          task_id: "$2"
      - match: 'airflow\.dag_processing\.last_duration\.(.*)'
        match_type: "regex"
        name: "airflow.dag_processing.last_duration"
        tags:
          dag_file: "$1"
      - match: 'airflow\.dagrun\.duration\.success\.(.*)'
        match_type: "regex"
        name: "airflow.dagrun.duration.success"
        tags:
          dag_id: "$1"
      - match: 'airflow\.dagrun\.duration\.failed\.(.*)'
        match_type: "regex"
        name: "airflow.dagrun.duration.failed"
        tags:
          dag_id: "$1"
      - match: 'airflow\.dagrun\.schedule_delay\.(.*)'
        match_type: "regex"
        name: "airflow.dagrun.schedule_delay"
        tags:
          dag_id: "$1"
      - match: 'airflow.scheduler.tasks.running'
        name: "airflow.scheduler.tasks.running"
      - match: 'airflow.scheduler.tasks.starving'
        name: "airflow.scheduler.tasks.starving"
      - match: 'airflow.sla_email_notification_failure'
        name: 'airflow.sla_email_notification_failure'
      - match: 'airflow\.task_removed_from_dag\.(.*)'
        match_type: "regex"
        name: "airflow.dag.task_removed"
        tags:
          dag_id: "$1"
      - match: 'airflow\.task_restored_to_dag\.(.*)'
        match_type: "regex"
        name: "airflow.dag.task_restored"
        tags:
          dag_id: "$1"
      - match: "airflow.task_instance_created-*"
        name: "airflow.task.instance_created"
        tags:
          task_class: "$1"
      - match: "airflow.ti.start.*.*"
        name: "airflow.ti.start"
        tags:
          dag_id: "$1"
          task_id: "$2"
      - match: "airflow.ti.finish.*.*.*"
        name: "airflow.ti.finish"
        tags:
          dag_id: "$1"
          task_id: "$2"
          state: "$3"
```

# Name of the image
I believe `ap-dogstatsd` would be a good suggestion. It should follow whatever default versioning scheme for the images in this repo.
