### ISSUE TITLE
dogstatsd: dogstatsd.yaml configuration has mapping entry that needs to be fixed

### ISSUE THREAD

**Issue by howardyoo** [astronomer/ap-vendor#423]
# Problem
This file, as part of the dogstatsd ap-vendor image:
https://github.com/astronomer/ap-vendor/blob/main/dogstatsd/include/dogstatsd.yaml
is from datadog's website found here: https://docs.datadoghq.com/integrations/airflow/?tab=host

The mapping works fine, except for cases where the task is included into a task group, and because of that, the name would have aditional `.` character. The mapping rule that is defined as:

```
      - match: "airflow.ti.start.*.*"
        name: "airflow.ti.start"
        tags:
          dag_id: "$1"
          task_id: "$2"
```

Does seem to not function properly, and skips processing because of that. The same issue is going to exist for any mapping rules that are going to be processing anything related to `task_id` (e.g. airflow.ti.finish)

# Solution

Contacted DataDog support to come up with a fixed version of this - or we can fix it by ourselves if that takes too long by replacing that with 
```
- match: "airflow\.ti\.start\.([^\.]*)\.(.*)"
```
