### ISSUE TITLE
remap metric airflow.local_task_job.* from incoming metrics list

### ISSUE THREAD

**Issue by howardyoo** [astronomer/ap-vendor#507]
# Problem
When datadog integration is enabled for Astro, you may observe the following metrics in the metrics summary list of datadog:
<img width="517" alt="image" src="https://user-images.githubusercontent.com/32691630/229220002-b97dbd7a-c5f4-45b5-9f82-85056163d115.png">
The metric `airflow.local_task_job.*` is mentioned in airflow documentation as such: https://airflow.apache.org/docs/apache-airflow/2.5.1/administration-and-deployment/logging-monitoring/metrics.html#counters, however, there is little use for it, and moreover, this metric is not part of the metric list that datadog airflow integration has in its documentation (https://docs.datadoghq.com/integrations/airflow/?tab=host#metrics).

Also, this metric is not something that is frequently used, since the metric is only emitted when a task is explicitly run via airflow task run command, and also, the metric is only used to check whether the metric has run or got stuck somewhere (if it is stuck, you won't see the metric itself, and if it exited with some exit code, you should see the exit code other than zero).

This metric is also problematic as it introduces high cardinality metrics - and also occupies metric namespace heavily.

# Solution
Add a mapping rule in dogstat's default rule config - such that it will remove these metrics from being emitted.
```yaml
      - match: 'airflow.local_task_job.task_exit.*.*.*.*'
        name: "airflow.local_task_job.task_exit"
        tags:
          dag_id: "$2"
          task_id: "$3"
          exit_code: "$4"
```
